### ISSUE TITLE
Iterator for environment

### ISSUE THREAD

**Issue by AYAN-AMBESH** [AYAN-AMBESH/LTW#1]
## Need to iterate through the environment of JSON data

**Comment by nparashar150** [comment]
Hey @AYAN-AMBESH, 
Can I take up the issue? And It will be really helpful if you can explain the issue in a bit of detail.

**Comment by AYAN-AMBESH** [comment]
yes sure @nparashar150 
I need to iterate through the below JSON data only in env
![JSon](https://user-images.githubusercontent.com/51339999/199766343-1d5e0bad-a78a-477f-bed1-d93729a8cbeb.png)
